### ISSUE TITLE
Double icons on message context menu

### ISSUE THREAD

**Issue by KTibow** [CreArts-Community/Context-Icons#19]
I'm using the CreArts theme with GooseMod. When I right-click a message, I see icons twice:
![image](https://user-images.githubusercontent.com/10727862/182173309-b9a1b474-2c4f-4d18-b8ee-2a29c268749c.png)
Could you remove the ones built in to Discord for consistency?

**Comment by KTibow** [comment]
Some CSS does the trick:
```css
.item-1OdjEX:not(#message-add-reaction):not(#message-apps) > .iconContainer-1-SsTR {
  display: none;
}
```
